name: Compile Master Branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    name: Compile ${{ matrix.prog }} for ${{ matrix.dist }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dist: [ubuntu_x86_64, macos_x86_64, win_x86_64]
        prog: [ctrtool, makerom]
        include:
         - dist: win_x86_64
           os: windows-2016
           binExt: .exe
         - dist: ubuntu_x86_64
           os: ubuntu-latest
         - dist: macos_x86_64
           os: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile ${{ matrix.prog }}
      run: cd ${{ matrix.prog }}; make ${{ matrix.makeArgs }};
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.prog }}-${{ matrix.dist }}
        path: ${{ matrix.prog }}/${{ matrix.prog }}${{ matrix.binExt }}